@startuml
'https://plantuml.com/sequence-diagram

autonumber

Aさん -> MagicOnion: 入室
MagicOnion <- Bさん: 入室
Aさん <-- MagicOnion: Bさんの入室通知を送信

敵 -> Aさん:出現
Aさん->MagicOnion:出現通知
Bさん <-- MagicOnion:出現通知
敵 -> Aさん:移動、回転
Aさん -> MagicOnion:移動回転通知
Bさん <-- MagicOnion:移動回転通知

Aさん -> 敵 :倒す
Aさん <- 敵 :倒された
Aさん -> MagicOnion:敵撃破通知
Bさん <-- MagicOnion:敵撃破通知
@enduml